config/routes.rb
Explainer::Application.routes.draw do
  get '/lessons' => 'pages#lessons'
  get '/series' => 'pages#series'
  get '/community' => 'pages#community'
  get '/clubs' => 'pages#clubs'

  root 'pages#home'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def lessons
  end

  def series
  end

  def community
  end

  def clubs
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Explainer</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
    <%= link_to 'lessons', lessons_path %>
    <%= link_to 'series', series_path %>
    <%= link_to 'community', community_path %>
    <%= link_to 'clubs', clubs_path %>
  </nav>
<%= yield %>

</body>
</html>

app/views/pages/clubs.html.erb
<h1>Clubs</h1>
<p>paragraph</p>

app/views/pages/community.html.erb
<h1>Community</h1>
<p>paragraph</p>

app/views/pages/home.html.erb
<h1>Explainer Home</h1>


It's <%= Time.now.strftime('%l:%M %p on %A') %>

app/views/pages/lessons.html.erb
<h1>Lessons</h1>
  <section>
    <h4>Filter by</h4>
    <h3>Content ˇ   Duration ˇ</h3>
    <h4>Sort by Publish Date ˇ</h4>
    <nav>
<!--
    <ul>
      <%# us something like this fo the auto generated categories %>
      <%# stand in text below, for now %>
      <%# zombies.each do |zombie| %>
        <li>
          <%#= zombie.name %>
          <%# if zombie.tweets.count > 1 %>
          SMART ZOMBIE
          <%# end %>
        </li>
      <%# end %>
    </ul>
-->
        All<br />
        Science & Technology<br />
        The Arts<br />
        Mathematics<br />
        Literature & Language<br />
    </nav>
  </section>
<article>
  <h3>Vid Title</h3>
    <p>Description</p>
</article>

app/views/pages/series.html.erb
<h1>Series</h1>
<p>paragraph</p>